/*
 * Copyright (C) 2011 divde <divde@free.fr>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.free.divde.brasouverts.dbui;

import fr.free.divde.brasouverts.db.BrasOuvertsDB;
import java.sql.Driver;
import java.util.Set;
import java.util.prefs.Preferences;
import javax.swing.JComboBox;
import org.openide.util.Lookup;
import org.openide.util.NbPreferences;

final class DatabasePanel extends javax.swing.JPanel {
    
    private final DatabaseOptionsPanelController controller;
    
    DatabasePanel(DatabaseOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdbcDriverLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jdbcDriverField = initJdbcDrivers();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        resetDefaultsButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jdbcDriverLabel, org.openide.util.NbBundle.getMessage(DatabasePanel.class, "DatabasePanel.jdbcDriverLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(urlLabel, org.openide.util.NbBundle.getMessage(DatabasePanel.class, "DatabasePanel.urlLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(userNameLabel, org.openide.util.NbBundle.getMessage(DatabasePanel.class, "DatabasePanel.userNameLabel.text")); // NOI18N

        jdbcDriverField.setEditable(true);

        org.openide.awt.Mnemonics.setLocalizedText(passwordLabel, org.openide.util.NbBundle.getMessage(DatabasePanel.class, "DatabasePanel.passwordLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(resetDefaultsButton, org.openide.util.NbBundle.getMessage(DatabasePanel.class, "DatabasePanel.resetDefaultsButton.text")); // NOI18N
        resetDefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDefaultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetDefaultsButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdbcDriverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(urlLabel)
                            .addComponent(passwordLabel)
                            .addComponent(userNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordField)
                            .addComponent(userNameField)
                            .addComponent(urlField)
                            .addComponent(jdbcDriverField, 0, 272, Short.MAX_VALUE))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdbcDriverLabel)
                    .addComponent(jdbcDriverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLabel)
                    .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetDefaultsButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void resetDefaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDefaultsButtonActionPerformed
    BrasOuvertsDB.resetConnectionPreferences();
    controller.update();
}//GEN-LAST:event_resetDefaultsButtonActionPerformed
    
    void load() {
        BrasOuvertsDB.checkConnectionPreferences();
        Preferences prefs = NbPreferences.forModule(BrasOuvertsDB.class);
        jdbcDriverField.setSelectedItem(prefs.get("javax.persistence.jdbc.driver", ""));
        urlField.setText(prefs.get("javax.persistence.jdbc.url", ""));
        userNameField.setText(prefs.get("javax.persistence.jdbc.user", ""));
        passwordField.setText(prefs.get("javax.persistence.jdbc.password", ""));
    }
    
    void store() {
        Preferences prefs = NbPreferences.forModule(BrasOuvertsDB.class);
        prefs.put("javax.persistence.jdbc.driver", jdbcDriverField.getSelectedItem().toString());
        prefs.put("javax.persistence.jdbc.url", urlField.getText());
        prefs.put("javax.persistence.jdbc.user", userNameField.getText());
        prefs.put("javax.persistence.jdbc.password", passwordField.getText());
    }
    
    boolean valid() {
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jdbcDriverField;
    private javax.swing.JLabel jdbcDriverLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton resetDefaultsButton;
    private javax.swing.JTextField urlField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables

    private JComboBox initJdbcDrivers() {
        Lookup.Result<Driver> drivers = Lookup.getDefault().lookupResult(Driver.class);
        Set<Class<? extends Driver>> classes = drivers.allClasses();
        String[] suggestions = new String[classes.size()];
        int i = 0;
        for (Class<? extends Driver> driver : classes) {
            suggestions[i] = driver.getName();
            i++;
        }
        JComboBox res = new JComboBox(suggestions);
        return res;
    }
}
